import turtle
turtle.color('magenta')
turtle.shape("turtle")
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(60)
turtle.circle(58)
turtle.left(60)
turtle.forward(50)
turtle.circle(29)
turtle.left(90)
turtle.forward(88)
turtle.backward(118)
turtle.pensize(15)
turtle.color("Cyan")
turtle.penup()
turtle.backward(20)
turtle.pendown()
turtle.backward(200)
turtle.penup()
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.pendown()
turtle.forward(150)
turtle.right(90)
turtle.forward(60)
turtle.backward(150)
turtle.penup()
turtle.goto(25, -280)

turtle.color("black")
turtle.write("Information Technology", font = ("Arial", 10))





turtle.exitonclick()