name = input("Введите Ваше имя: ")
surname = input("Введите Вашу фамилию: ")
year = int(input("Введите год рождения: "))
city = input("Введите город проживания: ")
hobby = input("Введите Ваше хобби: ")
color = input("Введите Ваш любимый цвет: ")
car = input("Введите марку любимой машины: ")

print("Обрабатываем информацию...")
print("Имя: ", name)
print("Фамилия: ", surname)
print("Возраст: ", 2022 - year)
print("Город: ", city)
print("Хобби: ", hobby)
print("Любимый цвет: ", color)
print("Любимая марка машины: ", car)